import { dashboardMetrics, hazardWorkflowSteps, mockPlatformSummary } from "@/data/mockDashboard";
import type { FeatureCardModel, MetricCardModel, RouteMeta } from "@/types/navigation";

function metric(label: string, value: string, hint: string, trend?: string, risk?: MetricCardModel["risk"]): MetricCardModel {
  return { label, value, hint, trend, risk };
}

function card(title: string, description: string, status = "mock 展示", tone: FeatureCardModel["tone"] = "neutral"): FeatureCardModel {
  return { title, description, status, tone };
}

const sharedNotes = ["当前页面仅使用 mock 数据或静态说明，不接真实后端、真实监测流或真实告警服务。"];

export const routes: RouteMeta[] = [
  {
    path: "/",
    title: "煤与瓦斯突出预警平台",
    module: "系统入口",
    description: `进入 ${mockPlatformSummary.mineName} 的安全管理控制台，当前阶段展示路由骨架、导航和 mock 摘要。`,
    status: "入口已创建",
    metrics: [
      metric("当前版本", "前端工作树", "路由骨架 + 布局系统 + 导航", "采用 frontend/src/app"),
      metric("演示矿井", mockPlatformSummary.mineName, "静态 mock 入口信息"),
      metric("更新时间", mockPlatformSummary.updatedAt, "模拟更新时间，不代表真实在线数据"),
    ],
    cards: [
      card("进入综合驾驶舱", "主入口指向 /dashboard，用于查看全局风险态势占位。", "可导航", "info"),
      card("安全态势摘要", "保留轻量概览，避免在根路由堆叠完整业务大屏。"),
      card("数据边界", "入口页不接登录、告警、后端或真实生产服务。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/dashboard",
    title: "综合驾驶舱",
    module: "综合驾驶舱",
    description: "汇总矿井安全态势、重点区域、近期预警趋势、待办处置和数据更新时间。",
    status: "驾驶舱骨架",
    metrics: dashboardMetrics,
    cards: [
      card("重点区域风险排行", "展示区域风险排序占位，后续由 mock 区域列表驱动。"),
      card("近期预警趋势", "保留趋势图容器，使用 mock 图表呈现。"),
      card("待办处置任务", "展示待核查、待整改、待验收的任务摘要。", "mock 待办", "info"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/monitoring",
    title: "监测概览",
    module: "实时监测与预警",
    description: "作为监测侧入口，展示通道健康摘要、实时监测入口、通道管理入口和异常波动提示。",
    status: "模块入口",
    metrics: [
      metric("节点总数", "63", "后端 63 节点模型口径", "来自 FastAPI", "low"),
      metric("在线率", "93%", "mock 健康统计"),
      metric("异常波动", "2", "待复核波动片段", "不触发真实告警", "normal"),
    ],
    cards: [
      card("实时监测入口", "跳转 /monitoring/realtime 查看 63 节点最新值与聚合曲线。"),
      card("通道管理入口", "跳转 /monitoring/channels 查看通道类型、区域、校验状态。"),
      card("异常摘要", "展示最近波动说明，后续接入 mock 时间序列。", "演示数据", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/monitoring/realtime",
    title: "传感器实时监测",
    module: "实时监测与预警",
    description: "展示后端 63 节点模型数据、关键指标聚合曲线、最新采样时间和异常波动提示。",
    status: "实时页占位",
    metrics: [
      metric("模型节点", "63", "后端 63 节点模型口径", "通过聚合接口读取", "low"),
      metric("最新采样", "09:30", "mock 采样时间"),
      metric("最新节点", "63", "每节点最新值", "来自 sensors/latest", "normal"),
      metric("异常片段", "2", "模拟波动提示", "待人工复核", "high"),
    ],
    cards: [
      card("关键曲线容器", "当前仅保留曲线展示区，使用 mock 图表呈现。"),
      card("通道健康矩阵", "展示在线、校验、维护责任人等健康维度。"),
      card("异常波动提示", "所有异常均为演示占位，不代表真实生产结论。", "mock", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/monitoring/channels",
    title: "监测通道管理",
    module: "实时监测与预警",
    description: "展示通道列表、通道类型、所属区域、在线状态、最近更新时间、校验状态和维护责任人。",
    status: "通道台账骨架",
    metrics: [
      metric("节点列表", "63", "后端 63 节点配置展示"),
      metric("待校验", "1", "mock 校验状态", "不执行真实校准", "normal"),
      metric("维护责任人", "4 组", "静态责任分组"),
    ],
    cards: [
      card("通道表格", "后续以 mock 通道清单补齐字段、筛选和详情入口。"),
      card("区域映射", "展示通道所属区域的静态映射关系。"),
      card("维护说明", "仅展示责任人和校验占位，不提供真实启停、删除或校准操作。", "禁止写入", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/warning",
    title: "预警概览",
    module: "实时监测与预警",
    description: "展示预警总览、风险等级分布、待处置数量、事件列表入口和最新高风险事件摘要。",
    status: "模块入口",
    metrics: [
      metric("预警事件", "6", "mock 事件统计", "含 2 条较大风险", "high"),
      metric("待处置", "4", "演示处置队列"),
      metric("最高等级", "较大", "风险四色统一", "橙色标识", "high"),
    ],
    cards: [
      card("事件列表入口", "跳转 /warning/events 查看预警编号、等级、区域和处置状态。"),
      card("风险等级分布", "保留风险四色分布区域。"),
      card("高风险摘要", "仅展示 mock 摘要，不触发真实通知。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/warning/events",
    title: "预警事件列表",
    module: "实时监测与预警",
    description: "展示事件编号、风险等级、事件时间、区域、关联通道、处置状态、负责人、筛选与检索。",
    status: "列表骨架",
    metrics: [
      metric("事件条目", "12", "mock 表格行数"),
      metric("待确认", "3", "演示处置状态", "人工复核", "normal"),
      metric("较大风险", "2", "风险四色统一", "需关注", "high"),
    ],
    cards: [
      card("筛选检索", "保留风险等级、区域、处置状态和负责人筛选入口。"),
      card("事件表格", "后续以 mock 事件表格补齐字段。"),
      card("详情跳转", "详情示例入口为 /warning/events/W001。", "可导航", "info"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/warning/events/[id]",
    title: "预警事件详情",
    module: "实时监测与预警",
    description: "展示单个预警事件基础信息、风险等级、关联区域、关联通道曲线、处置进度、溯源入口和处置建议。",
    status: "详情骨架",
    metrics: [
      metric("事件编号", "EVT-MOCK", "由动态路由承载"),
      metric("处置进度", "3/5", "mock 处置记录"),
      metric("关联通道", "4", "静态曲线容器"),
    ],
    cards: [
      card("事件基础信息", "展示风险等级、区域、时间和责任人。"),
      card("关联通道曲线", "当前提供曲线展示容器。"),
      card("溯源入口", "跳转溯源详情占位，不调用真实模型。", "mock", "info"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/source-tracing",
    title: "预警溯源总览",
    module: "预警溯源分析",
    description: "展示最近预警的注意力权重、主要贡献指标、疑似危险源、致因链路和事件详情跳转。",
    status: "溯源骨架",
    metrics: [
      metric("贡献指标", "8", "mock 注意力排行"),
      metric("疑似危险源", "3", "需人工复核", "辅助解释", "normal"),
      metric("关联事件", "5", "演示事件关联"),
    ],
    cards: [
      card("注意力权重入口", "跳转 /source-tracing/attention 查看指标贡献解释。"),
      card("致因链路", "展示气体、压力、地质和作业因素的链路占位。"),
      card("解释边界", "溯源结果为辅助解释，不写成最终事故原因。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/source-tracing/attention",
    title: "注意力权重解释",
    module: "预警溯源分析",
    description: "展示指标贡献排行、时间窗口、关联传感器、贡献变化趋势和辅助解释说明。",
    status: "解释页骨架",
    metrics: [
      metric("权重窗口", "30 min", "mock 时间窗口"),
      metric("贡献指标", "8", "静态指标字典"),
      metric("关联传感器", "4", "演示关联关系"),
    ],
    cards: [
      card("指标贡献排行", "展示注意力权重表格占位。"),
      card("贡献变化趋势", "使用 mock 趋势图表达。"),
      card("辅助解释说明", "明确不实时调用模型解释接口。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/source-tracing/events/[id]",
    title: "溯源事件详情",
    module: "预警溯源分析",
    description: "展示指定事件摘要、注意力权重、危险源定位、致因链路、关联隐患和回到预警详情入口。",
    status: "详情骨架",
    metrics: [
      metric("溯源编号", "SRC-MOCK", "动态路由占位"),
      metric("关联隐患", "2", "mock 关联记录"),
      metric("解释状态", "待复核", "辅助分析结果", "人工确认", "normal"),
    ],
    cards: [
      card("危险源定位", "展示危险源位置和理由摘要占位。"),
      card("致因链路", "以卡片展示因素关系，不接真实图数据库。"),
      card("回到预警详情", "保留与 /warning/events/W001 的导航关系。"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/regions",
    title: "区域风险中心",
    module: "区域风险中心",
    description: "展示区域名称、风险等级、隐患数量、预警数量、最近更新时间、管控状态和详情入口。",
    status: "区域列表骨架",
    metrics: [
      metric("区域数量", "6", "mock 区域列表"),
      metric("重点区域", "2", "较大风险及以上", "需关注", "high"),
      metric("闭环中隐患", "9", "演示治理数据"),
    ],
    cards: [
      card("区域表格", "后续补齐区域名称、风险等级、预警数和管控状态。"),
      card("详情入口", "区域详情示例入口为 /regions/R001。", "可导航", "info"),
      card("管控状态", "展示区域管控摘要，不读取真实矿图。", "mock", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/regions/[regionId]",
    title: "区域风险详情",
    module: "区域风险中心",
    description: "展示区域基础信息、当前风险等级、传感器分布、关联隐患、管控措施、预警历史和闭环进度。",
    status: "详情骨架",
    metrics: [
      metric("当前风险", "一般", "mock 区域等级", undefined, "normal"),
      metric("传感器点位", "7", "静态点位占位"),
      metric("闭环进度", "68%", "mock 隐患治理"),
    ],
    cards: [
      card("区域基础信息", "展示区域名称、位置说明和责任班组。"),
      card("传感器分布", "仅展示脱敏 mock 点位，不使用真实空间信息。"),
      card("关联隐患", "展示隐患摘要和闭环状态。"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention",
    title: "双重预防总览",
    module: "双重预防机制",
    description: "展示风险分级管控状态、隐患排查治理状态、闭环效率、逾期事项、区域风险矩阵和重点待办。",
    status: "双控骨架",
    metrics: [
      metric("风险管控项", "28", "mock 风险清单"),
      metric("隐患治理中", "11", "八步闭环治理"),
      metric("闭环效率", "86%", "演示统计", "本周 +4%", "low"),
      metric("逾期事项", "2", "待升级占位", "需跟进", "high"),
    ],
    cards: [
      card("风险矩阵", "展示四色综合风险分布占位。"),
      card("重点待办", "展示待整理、待整改、待验收事项。"),
      card("复盘独立", "复盘入口独立在 /double-prevention/review，不并入八步闭环。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/risk-control",
    title: "风险分级管控",
    module: "双重预防机制",
    description: "展示风险辨识清单、风险等级、责任单位、管控措施、检查频次和状态更新入口。",
    status: "风险清单骨架",
    metrics: [
      metric("风险项", "28", "mock 风险清单"),
      metric("较大及以上", "5", "四色等级统一", undefined, "high"),
      metric("责任单位", "6", "静态组织占位"),
    ],
    cards: [
      card("风险辨识清单", "后续以 mock 风险列表补齐等级、单位和措施。"),
      card("风险四色规则", "统一低风险蓝、一般黄、较大橙、重大红。"),
      card("管控措施", "展示措施摘要，不写入真实风险库。", "禁止写入", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/risk-map",
    title: "风险四色图",
    module: "双重预防机制",
    description: "展示区域风险分布、四色图例、风险点摘要、区域筛选和风险详情入口。",
    status: "四色图骨架",
    metrics: [
      metric("风险网格", "24", "mock 区域网格"),
      metric("重大风险点", "1", "红色统一标识", undefined, "critical"),
      metric("区域筛选", "6", "静态区域选项"),
    ],
    cards: [
      card("四色图例", "蓝、黄、橙、红风险等级统一展示。"),
      card("风险点摘要", "展示 mock 风险点和详情入口。"),
      card("空间边界", "不使用真实矿区精确坐标。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/risk-cards",
    title: "风险告知卡",
    module: "双重预防机制",
    description: "展示风险卡编号、风险名称、风险等级、所在区域、责任单位、管控措施摘要和详情入口。",
    status: "列表骨架",
    metrics: [
      metric("告知卡", "18", "mock 卡片列表"),
      metric("待复核", "3", "演示状态"),
      metric("责任单位", "5", "静态单位字典"),
    ],
    cards: [
      card("告知卡列表", "以统一卡片和表格承载风险编号、名称、等级和措施。"),
      card("详情入口", "详情示例入口为 /double-prevention/risk-cards/RC001。"),
      card("发布边界", "不生成正式盖章告知卡。", "禁止正式发布", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/risk-cards/[id]",
    title: "风险告知卡详情",
    module: "双重预防机制",
    description: "展示风险名称、风险等级、风险描述、管控措施、应急处置、责任人、检查频次和关联隐患。",
    status: "详情骨架",
    metrics: [
      metric("风险等级", "较大", "mock 风险卡详情", undefined, "high"),
      metric("管控措施", "4", "静态措施摘要"),
      metric("关联隐患", "2", "mock 关联记录"),
    ],
    cards: [
      card("风险描述", "展示风险来源、影响范围和等级说明。"),
      card("管控措施", "展示措施摘要和检查频次。"),
      card("应急处置", "仅展示占位说明，不替代线下安全确认。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/measure-library",
    title: "管控措施库",
    module: "双重预防机制",
    description: "展示措施分类、适用风险、执行频次、责任角色、检查要点和引用入口。",
    status: "措施库骨架",
    metrics: [
      metric("措施条目", "42", "mock 措施库"),
      metric("引用关系", "18", "演示风险关联"),
      metric("措施分类", "6", "静态分类"),
    ],
    cards: [
      card("措施分类", "按通风、瓦斯、地质、作业等分类展示。"),
      card("检查要点", "展示执行频次、责任角色和检查要点。"),
      card("引用入口", "仅保留引用占位，不写入真实措施库。", "mock", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/hazard-governance",
    title: "隐患排查治理",
    module: "双重预防机制",
    description: "展示隐患统计、来源分类、治理状态分布、重点隐患、治理趋势、台账与流程入口。",
    status: "治理总览骨架",
    metrics: [
      metric("隐患总数", "31", "mock 隐患统计"),
      metric("治理中", "11", "八步闭环中"),
      metric("重点隐患", "3", "需关注", undefined, "high"),
    ],
    cards: [
      card("治理状态分布", "展示整理、整改、验收等状态占位。"),
      card("重点隐患", "展示需跟进隐患摘要。"),
      card("流程入口", "跳转八步闭环页面，顺序不可改写。", "可导航", "info"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/hazard-ledger",
    title: "隐患台账",
    module: "双重预防机制",
    description: "展示隐患编号、描述、风险等级、所属区域、责任人、当前步骤、期限、逾期状态和详情入口。",
    status: "台账骨架",
    metrics: [
      metric("台账记录", "31", "mock 隐患台账"),
      metric("逾期", "2", "演示逾期状态", undefined, "high"),
      metric("待验收", "4", "闭环步骤枚举"),
    ],
    cards: [
      card("隐患表格", "后续补齐编号、等级、区域、责任人与当前步骤。"),
      card("闭环步骤", "步骤固定为整理、分析、通报、整改、反馈、验收、审查、销号。"),
      card("详情入口", "详情示例入口为 /double-prevention/hazard-ledger/H001。"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/hazard-ledger/[id]",
    title: "隐患台账详情",
    module: "双重预防机制",
    description: "展示隐患基础信息、八步闭环进度、整改材料摘要、验收记录、审查记录、销号状态和关联预警。",
    status: "详情骨架",
    metrics: [
      metric("当前步骤", "整改", "mock 流程记录", undefined, "normal"),
      metric("材料摘要", "3", "不上传真实材料"),
      metric("关联预警", "2", "mock 事件关联"),
    ],
    cards: [
      card("八步进度", "严格使用固定八步，不加入复盘。"),
      card("整改材料摘要", "仅展示 mock 摘要，不支持真实上传。"),
      card("验收与审查", "保留记录占位和销号状态。"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/hazard-workflow",
    title: "隐患八步闭环",
    module: "双重预防机制",
    description: "严格展示隐患排查治理固定八步：整理、分析、通报、整改、反馈、验收、审查、销号。",
    status: "八步固定",
    metrics: [
      metric("固定步骤", "8", "不得增删或改序"),
      metric("当前流转", "11", "mock 闭环任务"),
      metric("复盘位置", "独立", "复盘仅在 /double-prevention/review", undefined, "low"),
    ],
    cards: [
      card("责任人与时间", "每一步预留责任人、时间、材料和状态展示位。"),
      card("材料摘要", "展示通报、整改、反馈、验收等材料占位。"),
      card("下一步提示", "只做 mock 提示，不触发真实流程。", "mock", "warning"),
    ],
    workflowSteps: hazardWorkflowSteps,
    notes: ["复盘不得作为第九步加入八步闭环。", ...sharedNotes],
  },
  {
    path: "/double-prevention/overdue-escalation",
    title: "逾期升级",
    module: "双重预防机制",
    description: "展示逾期隐患列表、逾期天数、责任人、升级级别、通知策略和处理建议。",
    status: "升级骨架",
    metrics: [
      metric("逾期隐患", "2", "mock 逾期列表", undefined, "high"),
      metric("最高逾期", "5 天", "演示天数"),
      metric("升级规则", "3", "静态规则"),
    ],
    cards: [
      card("逾期列表", "展示隐患编号、责任人、逾期天数和当前步骤。"),
      card("升级策略", "展示静态升级级别和通知策略。"),
      card("通知边界", "不发送真实短信、电话、企业微信或邮件。", "禁止通知", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/review",
    title: "复盘追溯",
    module: "双重预防机制",
    description: "独立展示预警事件复盘、隐患处置复盘、管控措施执行效果、复盘结论、改进建议和追踪状态。",
    status: "复盘独立",
    metrics: [
      metric("复盘案例", "7", "mock 案例列表"),
      metric("改进建议", "12", "演示追踪"),
      metric("追踪中", "5", "不并入八步闭环"),
    ],
    cards: [
      card("预警事件复盘", "展示事件复盘入口和摘要。"),
      card("隐患处置复盘", "独立于八步闭环展示。", "边界已标识", "info"),
      card("改进追踪", "展示建议和状态，不生成正式事故调查结论。", "mock", "warning"),
    ],
    notes: ["复盘独立存在，不写入 /double-prevention/hazard-workflow 的八步闭环。", ...sharedNotes],
  },
  {
    path: "/double-prevention/config",
    title: "双重预防配置",
    module: "双重预防机制",
    description: "展示风险等级规则、隐患流程配置、逾期升级规则、责任组织、通知策略和文化展板内容配置入口。",
    status: "配置骨架",
    metrics: [
      metric("规则项", "18", "mock 配置项"),
      metric("组织节点", "6", "静态组织结构"),
      metric("通知策略", "4", "占位，不接真实渠道"),
    ],
    cards: [
      card("风险等级规则", "展示四色规则和阈值占位。"),
      card("隐患流程配置", "仅展示配置说明，不改变固定八步顺序。"),
      card("保存边界", "不保存真实系统配置或通知渠道。", "禁止写入", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/double-prevention/culture-board",
    title: "双控文化展板",
    module: "双重预防机制",
    description: "展示安全理念、双控流程、风险四色说明、隐患闭环八步、优秀整改案例和班组宣传内容。",
    status: "展板骨架",
    metrics: [
      metric("宣传内容", "8", "静态展板条目"),
      metric("优秀案例", "3", "mock 案例摘要"),
      metric("风险四色", "4", "统一图例"),
    ],
    cards: [
      card("安全理念", "展示双重预防文化宣传内容。"),
      card("闭环八步", "展示整理至销号，不包含复盘。"),
      card("边界区分", "不与 /knowledge/culture-board 的知识库内容混同。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/twin",
    title: "数字孪生入口",
    module: "数字孪生可视化",
    description: "展示巷道总览入口、风险热力图入口、传感器点位入口和空间态势摘要。",
    status: "孪生壳占位",
    metrics: [
      metric("空间区域", "6", "mock 空间摘要"),
      metric("风险点", "9", "静态风险标注"),
      metric("3D 引擎", "未接入", "当前仅提供轻量壳层"),
    ],
    cards: [
      card("巷道总览入口", "跳转 /twin/tunnel 查看示意壳。"),
      card("风险热力入口", "跳转 /twin/risk-heatmap 查看 mock 热力。"),
      card("传感器点位入口", "跳转 /twin/sensors 查看点位清单。"),
    ],
    notes: ["数字孪生仅做轻量空间态势展示，不接 3D 引擎、真实定位或真实监测流。", ...sharedNotes],
  },
  {
    path: "/twin/tunnel",
    title: "巷道示意",
    module: "数字孪生可视化",
    description: "展示巷道示意视图、区域标注、风险点标注、视角控制占位和数据更新时间。",
    status: "示意壳",
    metrics: [
      metric("巷道段", "8", "静态示意模型"),
      metric("风险标注", "9", "mock 标注"),
      metric("视角控制", "占位", "不引入重型 3D 依赖"),
    ],
    cards: [
      card("巷道示意视图", "以轻量占位表达空间结构。"),
      card("区域标注", "展示区域和风险点说明。"),
      card("3D 边界", "不加载真实矿井三维模型或渲染任务。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/twin/risk-heatmap",
    title: "风险热力图",
    module: "数字孪生可视化",
    description: "展示区域热力分布、风险等级图例、时间窗口筛选和重点高风险区域列表。",
    status: "热力骨架",
    metrics: [
      metric("热力网格", "24", "mock 热力网格"),
      metric("高风险区域", "2", "静态列表", undefined, "high"),
      metric("时间窗口", "24h", "演示筛选"),
    ],
    cards: [
      card("热力分布", "展示 mock 热力容器。"),
      card("风险图例", "统一风险四色。"),
      card("预测边界", "mock 热力不得当作真实预测结果。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/twin/sensors",
    title: "传感器点位",
    module: "数字孪生可视化",
    description: "展示传感器点位列表、所属区域、通道类型、健康状态、最近上报时间和点位筛选。",
    status: "点位骨架",
    metrics: [
      metric("点位数量", "63", "后端 63 节点点位"),
      metric("健康状态", "后端", "最新值与空间位置"),
      metric("筛选维度", "3", "区域、类型、状态"),
    ],
    cards: [
      card("点位列表", "展示传感器编号、区域、通道类型和状态。"),
      card("点位筛选", "预留区域、通道类型和健康状态筛选。"),
      card("敏感边界", "不展示真实敏感点位或修改真实设备状态。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/knowledge",
    title: "知识库入口",
    module: "知识库与智能体",
    description: "展示标准规范检索入口、致灾路径图谱入口、文化展板入口、推荐知识和最近使用记录。",
    status: "知识入口",
    metrics: [
      metric("知识条目", "128", "mock 条目数量"),
      metric("推荐知识", "5", "静态推荐"),
      metric("最近访问", "6", "mock 访问记录"),
    ],
    cards: [
      card("规范检索入口", "跳转 /knowledge/search。"),
      card("致灾路径图谱", "跳转 /knowledge/causal-graph。"),
      card("文化展板入口", "跳转 /knowledge/culture-board，与双控文化展板保持边界。"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/knowledge/search",
    title: "标准规范检索",
    module: "知识库与智能体",
    description: "展示搜索框、分类筛选、规范条目列表、摘要、适用场景和详情占位。",
    status: "检索骨架",
    metrics: [
      metric("规范条目", "128", "mock 规范条目"),
      metric("分类", "9", "静态分类"),
      metric("适用场景", "12", "演示标签"),
    ],
    cards: [
      card("搜索框", "当前为静态输入展示。"),
      card("规范列表", "展示标题、摘要和适用场景。"),
      card("内容边界", "不联网检索，不展示未经授权全文材料。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/knowledge/causal-graph",
    title: "致灾路径图谱",
    module: "知识库与智能体",
    description: "展示风险因素节点、因果关系边、关联预警、关联隐患和节点详情面板。",
    status: "图谱骨架",
    metrics: [
      metric("因素节点", "16", "mock 图谱节点"),
      metric("关系边", "22", "静态因果边"),
      metric("关联预警", "5", "演示关联"),
    ],
    cards: [
      card("图谱节点", "展示瓦斯、压力、地质、作业等因素节点。"),
      card("关系边", "展示原因链路占位。"),
      card("结论边界", "图谱关系不写成最终事故因果认定。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/knowledge/culture-board",
    title: "知识文化展板",
    module: "知识库与智能体",
    description: "展示双重预防制度、标准规范、培训材料、案例知识和问答入口。",
    status: "展板骨架",
    metrics: [
      metric("培训材料", "10", "mock 材料"),
      metric("案例知识", "6", "静态摘要"),
      metric("问答入口", "1", "跳转 /agent"),
    ],
    cards: [
      card("制度知识", "面向学习和检索，不替代正式制度文本。"),
      card("案例知识", "展示案例摘要和学习入口。"),
      card("边界区分", "不与 /double-prevention/culture-board 混同。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/agent",
    title: "AI 问答入口",
    module: "知识库与智能体",
    description: "展示问答输入框、推荐问题、回答占位、引用知识占位、安全提示和历史会话摘要。",
    status: "问答占位",
    metrics: [
      metric("推荐问题", "6", "静态问题列表"),
      metric("引用占位", "3", "mock 知识引用"),
      metric("模型 API", "未接入", "不调用真实模型"),
    ],
    cards: [
      card("问答输入框", "仅提供输入区域视觉占位。"),
      card("回答占位", "展示回答结构，不生成真实模型回复。"),
      card("安全提示", "不得输出强制处置命令或替代人工安全判断。", "边界已标识", "warning"),
    ],
    notes: ["AI 问答入口不接真实大模型 API 或生产知识库。", ...sharedNotes],
  },
  {
    path: "/data",
    title: "数据管理入口",
    module: "数据与模型管理",
    description: "展示动态数据、静态数据、特征字典、数据集版本和数据增强入口与状态摘要。",
    status: "数据入口",
    metrics: [
      metric("数据资产", "5 类", "动态、静态、特征、数据集、增强"),
      metric("数据集版本", "4", "mock 版本摘要"),
      metric("数据增强", "展示", "仅展示结果和指标"),
    ],
    cards: [
      card("动态数据入口", "跳转 /data/dynamic。"),
      card("静态数据入口", "跳转 /data/static 和 /data/static/import。"),
      card("增强与模型入口", "跳转 /data/augmentation 和 /model。"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/data/dynamic",
    title: "动态监测数据",
    module: "数据与模型管理",
    description: "展示动态数据通道、采样频率、最近数据时间、质量状态和异常片段摘要。",
    status: "动态数据骨架",
    metrics: [
      metric("动态节点", "63", "后端 63 节点动态数据"),
      metric("采样频率", "1 min", "mock 频率说明"),
      metric("质量状态", "良好", "演示质量状态", undefined, "low"),
    ],
    cards: [
      card("通道摘要", "展示通道、采样频率和更新时间。"),
      card("质量状态", "展示缺失率、异常片段等占位。"),
      card("数据边界", "不读取真实监测库，不提供真实导出。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/data/static",
    title: "静态数据录入",
    module: "数据与模型管理",
    description: "展示区域、设备、传感器、岗位、责任单位、基础风险点等静态资料录入表单或表格。",
    status: "录入骨架",
    metrics: [
      metric("静态表", "6", "mock 资料类型"),
      metric("校验规则", "8", "静态字段说明"),
      metric("待修正", "3", "mock 校验结果", undefined, "normal"),
    ],
    cards: [
      card("资料表格", "展示区域、设备、岗位和责任单位字段。"),
      card("字段说明", "展示静态字段说明和校验规则。"),
      card("保存边界", "不保存到真实数据库，不上传敏感组织或人员信息。", "禁止写入", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/data/static/import",
    title: "静态数据导入",
    module: "数据与模型管理",
    description: "展示导入模板说明、文件上传占位、字段映射、校验结果、导入预览和错误下载占位。",
    status: "导入骨架",
    metrics: [
      metric("模板字段", "22", "静态模板说明"),
      metric("映射字段", "18", "mock 字段映射"),
      metric("校验错误", "3", "演示错误行", undefined, "normal"),
    ],
    cards: [
      card("文件上传占位", "仅展示上传区域，不进行真实文件上传。"),
      card("字段映射", "展示模板字段与系统字段映射。"),
      card("导入边界", "不写入真实数据表，不下载真实错误文件。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/data/features",
    title: "63 节点指标字典",
    module: "数据与模型管理",
    description: "展示指标名称、指标类型、来源通道、计算说明、单位、适用模型和数据边界。",
    status: "指标字典骨架",
    metrics: [
      metric("指标节点", "63", "后端模型节点字典"),
      metric("A 类节点", "22", "真实传感器/直接指标"),
      metric("B 类节点", "41", "派生与模型输入节点"),
    ],
    cards: [
      card("指标字典", "展示 63 节点指标名称、单位、类型和空间位置。"),
      card("来源节点", "按后端 meta_info 区分 A/B 节点和空间位置。"),
      card("边界说明", "前端展示后端节点口径，不再沿用 14+19 的旧展示口径。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/data/datasets",
    title: "数据集版本",
    module: "数据与模型管理",
    description: "展示数据集版本、时间范围、样本数量、通道覆盖、质量评分、关联模型和备注。",
    status: "版本骨架",
    metrics: [
      metric("数据集版本", "4", "mock 版本列表"),
      metric("节点覆盖", "63/63", "后端节点覆盖说明"),
      metric("质量评分", "91", "演示质量指标", undefined, "low"),
    ],
    cards: [
      card("版本列表", "展示版本号、时间范围、样本数量和备注。"),
      card("质量指标", "展示缺失率、覆盖率和质量评分占位。"),
      card("数据边界", "不下载真实数据集，不上传大型训练数据。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/data/augmentation",
    title: "数据增强展示",
    module: "数据与模型管理",
    description: "展示后端 63 节点模型口径、动态数据、事件台账、模型配置和推理结果说明。",
    status: "增强结果展示",
    metrics: [
      metric("模型节点", "63", "来自后端 meta_info", "后端节点口径", "low"),
      metric("事件台账", "写入", "推理结果进入 warning_results", "显式触发", "normal"),
      metric("指标维度", "63", "统一后端模型节点展示"),
      metric("验证指标", "AUC / KS", "含物理约束满足率、对抗验证 AUC、KS 检验通过率"),
    ],
    cards: [
      card("63 模型节点", "展示后端 63 节点清单和来源说明。"),
      card("推理写库", "前端按钮显式触发模型推理，后端写入事件台账。", "边界已标识", "warning"),
      card("验证指标占位", "物理约束满足率、对抗验证 AUC、KS 检验通过率将在后续用 mock 数据补齐。"),
      card("数据集版本", "展示增强结果关联的数据集版本和质量摘要。"),
    ],
    notes: [
      "生成通道为辅助前兆指标，不替代真实传感器监测。",
      "本页面不训练 WGAN-GP，不保存模型权重，不提交大型训练数据，不接真实训练队列。",
      ...sharedNotes,
    ],
  },
  {
    path: "/model",
    title: "模型管理入口",
    module: "数据与模型管理",
    description: "展示模型评估入口、模型版本入口、当前主模型摘要、关联数据版本和模型状态说明。",
    status: "模型入口",
    metrics: [
      metric("主模型", "MOCK-v1", "静态模型摘要"),
      metric("关联数据集", "DS-2026-06", "mock 数据版本"),
      metric("训练入口", "无", "前端不触发真实训练"),
    ],
    cards: [
      card("模型评估入口", "跳转 /model/evaluation。"),
      card("模型版本入口", "跳转 /model/version。"),
      card("模型边界", "不训练、部署、回滚或保存真实模型权重。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/model/evaluation",
    title: "模型评估",
    module: "数据与模型管理",
    description: "展示预警模型指标、混淆矩阵、召回率、误报率、消融实验、数据版本、模型版本、评估时间与局限性。",
    status: "评估骨架",
    metrics: [
      metric("召回率", "91%", "mock 评估指标", undefined, "low"),
      metric("误报率", "8%", "演示指标"),
      metric("混淆矩阵", "mock", "使用 mock 图表呈现"),
      metric("局限性", "已标识", "不作为正式验收指标"),
    ],
    cards: [
      card("核心指标", "展示召回率、误报率、AUC 等评估指标占位。"),
      card("混淆矩阵", "保留矩阵容器，后续接入 mock 数据。"),
      card("评估边界", "不调用真实评估任务，不把 mock 指标写成正式验收指标。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/model/version",
    title: "模型版本管理",
    module: "数据与模型管理",
    description: "展示模型版本号、训练数据版本、评估摘要、发布时间、状态、变更说明和回滚入口占位。",
    status: "版本骨架",
    metrics: [
      metric("模型版本", "3", "mock 版本列表"),
      metric("发布状态", "演示", "不连接模型仓库"),
      metric("回滚入口", "占位", "不执行真实回滚"),
    ],
    cards: [
      card("版本列表", "展示版本号、数据版本、评估摘要和变更说明。"),
      card("状态说明", "展示发布、观察、归档等 mock 状态。"),
      card("权重边界", "不上传、下载、部署或回滚真实模型权重。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/system",
    title: "系统管理入口",
    module: "系统管理",
    description: "展示用户权限、操作日志、系统配置入口与系统状态摘要。",
    status: "系统入口",
    metrics: [
      metric("用户角色", "5", "静态角色枚举"),
      metric("操作日志", "24", "mock 日志摘要"),
      metric("配置项", "12", "静态配置说明"),
    ],
    cards: [
      card("用户权限入口", "跳转 /system/users。"),
      card("操作日志入口", "跳转 /system/logs。"),
      card("系统配置入口", "跳转 /system/config，不接真实认证或审计系统。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/system/users",
    title: "用户权限管理",
    module: "系统管理",
    description: "展示用户列表、角色、所属单位、权限范围、状态、最近登录时间和操作占位。",
    status: "权限骨架",
    metrics: [
      metric("用户条目", "18", "mock 用户列表"),
      metric("角色", "5", "静态角色枚举"),
      metric("停用占位", "0", "不执行真实账号操作"),
    ],
    cards: [
      card("用户列表", "展示脱敏姓名、角色、单位和状态占位。"),
      card("权限范围", "展示静态权限说明。"),
      card("敏感边界", "不接真实用户系统，不展示真实个人敏感信息。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/system/logs",
    title: "操作日志",
    module: "系统管理",
    description: "展示操作时间、操作人、模块、动作、结果、风险级别、筛选与检索。",
    status: "日志骨架",
    metrics: [
      metric("日志条目", "24", "mock 日志列表"),
      metric("风险动作", "3", "演示风险级别", undefined, "normal"),
      metric("筛选项", "5", "模块、动作、结果、级别、时间"),
    ],
    cards: [
      card("日志表格", "展示时间、操作人、模块、动作和结果。"),
      card("筛选检索", "保留筛选和搜索占位。"),
      card("审计边界", "不接真实审计日志，不展示真实账号、IP 或敏感操作记录。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/system/config",
    title: "系统基础配置",
    module: "系统管理",
    description: "展示平台参数、矿井/区域选择、告警阈值占位、数据刷新策略和通知配置占位。",
    status: "配置骨架",
    metrics: [
      metric("平台参数", "12", "mock 配置项"),
      metric("刷新策略", "3", "静态策略"),
      metric("通知配置", "占位", "不接真实渠道"),
    ],
    cards: [
      card("平台参数", "展示矿井、区域、刷新策略等基础配置说明。"),
      card("告警阈值", "保留阈值说明区，不保存真实参数。"),
      card("通知配置", "不连接真实通知、认证或数据服务。", "边界已标识", "warning"),
    ],
    notes: sharedNotes,
  },
  {
    path: "/knowledge/overview",
    title: "知识库总览",
    module: "知识库与智能体",
    description: "接入 FastAPI 知识库后端，展示分类、高风险指标、统计与 Neo4j/PostgreSQL 连接状态。",
    status: "后端接入",
    metrics: [
      metric("数据来源", "FastAPI", "通过 Next.js API 代理访问", "浏览器不直连后端"),
      metric("连接状态", "实时", "Neo4j + PostgreSQL 状态检测", undefined, "normal"),
      metric("高风险指标", "—", "后端不可用时显示待连接", undefined, "high"),
    ],
    cards: [
      card("分类与高风险指标", "调用 /api/knowledge/categories、/api/knowledge/risk/high-risk 实时展示。"),
      card("知识库统计", "调用 /api/knowledge/stats 展示指标、规则、措施、案例、标准总量。"),
      card("连接边界", "前端不直连 Neo4j/PostgreSQL，统一通过 Next.js API 代理访问后端。", "边界已标识", "warning"),
    ],
    notes: [
      "本页通过 Next.js API 代理 /api/knowledge/* 转发到 FastAPI 后端 /api/*。",
      "后端不可用时返回 503，页面显示「待连接」状态。",
      sharedNotes[0],
    ],
  },
  {
    path: "/knowledge/rules",
    title: "规则指标库",
    module: "知识库与智能体",
    description: "支持关键词、动态/静态、分类筛选的指标检索，关联风险规则与管控措施。",
    status: "后端接入",
    metrics: [
      metric("数据来源", "FastAPI", "/api/indicators、/api/rules、/api/measures", "通过 Next.js 代理"),
      metric("筛选项", "3", "关键词、属性、分类"),
      metric("知识图谱", "预留", "指标卡片点击跳转图谱详情暂未实现", undefined, "normal"),
    ],
    cards: [
      card("指标卡片", "展示 id、name、threshold、category、risk_level、type。"),
      card("规则与措施", "并行展示风险规则与管控措施列表。"),
      card("图谱入口", "知识图谱详情跳转为本阶段预留入口。", "预留入口", "warning"),
    ],
    notes: [
      "指标数据由 Neo4j 提供，前端不直接访问数据库。",
      sharedNotes[0],
    ],
  },
  {
    path: "/knowledge/assistant",
    title: "智能问答",
    module: "知识库与智能体",
    description: "通过自然语言查询知识库，后端 /api/nl-query 解析意图并返回结构化结果。",
    status: "后端接入",
    metrics: [
      metric("数据来源", "FastAPI", "/api/nl-query?q=...", "通过 Next.js 代理"),
      metric("意图识别", "9 类", "查询指标、风险、分类、措施、标准等"),
      metric("展示形式", "结构化 JSON", "预留拆分卡片", undefined, "normal"),
    ],
    cards: [
      card("查询输入", "支持自然语言提问与示例快捷查询。"),
      card("结果展示", "结构化展示意图、数量与结果列表，附原始 JSON。"),
      card("卡片预留", "相关指标、阈值依据、处置措施、法规来源、相似案例预留入口。", "预留入口", "warning"),
    ],
    notes: [
      "查询由后端解析意图，前端不直接访问数据库。",
      sharedNotes[0],
    ],
  },
];

export const routeMetaByPath: Record<string, RouteMeta> = Object.fromEntries(
  routes.map((route) => [route.path, route]),
);
